version: "3.8"
services:
  transmission:
    build:
      context: .
      dockerfile: Dockerfile.alpine
    cap_add:
      - NET_ADMIN
    restart: always
    ports:
      - "9091:9091"
      - "52801:52801"
    dns:
      # DNS.watch resolvers for no censoring, logging, etc.
      - 84.200.69.80
      - 84.200.70.40
    env_file:
      - network.env
    secrets:
      - source: ovpn_client_creds
        mode: 0400
    volumes:
      - type: bind
        source: ~/torrents
        target: /data
        consistency: delegated
      - type: bind
        source: ./configs
        target: /configs
        read_only: true
  
  # combustion:
  #   build:
  #     context: ./combustion
  #   ports:
  #     - 80:8081
  #   links:
  #     - transmission

  # proxy:
  #   image: haugene/transmission-openvpn-proxy
  #   links:
  #     - transmission
  #   ports:
  #     - 8080:8080
  #   volumes:
  #     - /etc/localtime:/etc/localtime:ro

  # rss:
  #   image: nning2/transmission-rss
  #   links:
  #     - transmission
  #   volumes:
  #     - type: bind
  #       source: ./configs/transmission-rss/config.yml
  #       target: /etc/transmission-rss.conf

secrets:
    ovpn_client_creds:
        file: .secrets/openvpn/client_creds.txt